### ISSUE TITLE
Create Hall of Fame Page

### ISSUE THREAD

**Issue by darkboywonder** [darkboywonder/LAASHOF#34]
# Summary
We have a hall of fame but no where for users to see their stories.
See drawing for reference: 
https://www.tldraw.com/s/v2_c_H6-1PxSkDX-WJH7sMXZSa?viewport=-2435%2C1249%2C7789%2C3935&page=page%3A2fGUde_9zlcBN-yc_EVGH

## Tasks
- [ ] Create hall of fame index page that list hall of famers by class.
- [ ] Create a show page for each individual or team in the hall of fame that displays
    - [ ] photo
    - [ ] name
    - [ ] bio
    - [ ] category of induction
    - [ ] accolades
- [ ] Add a `Visit Hall of Fame` button the in the hall of fame section on the home page for users
- [ ] Add a Hall of Fame link at the top of the page
