### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by darkboywonder** [darkboywonder/LAASHOF#39]
# Summary
There are some tests that still need to be added to the site.

## Tasks
- [ ] Test `CreateUser` Command
- [ ] Test `Team Nomination` page
- [ ] Test registration and login flow
